language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - npm run start
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJ6VDWHDLG5BUIRFA
  secret_access_key:
    secure: "WJHv/+F9G1275pYVTY2QLiQL446MYWqgkotJF4MiDfUcLxiycF9vUhEWzh2vzXmkKSAZkYiO+bAldRIp1gNgT+M/fz3DJy/DN0qsLDm633owUSLZ8Bdjnk+xEXjk1PXxCEVbLOSsiLybF6z2P9xopSOLjL1RdP3Zlgy6ObtBZJ/A0PDNekDYb0y1ramp0u0zMpAFH5Cmg
WP5mJmGRFDs5pyDciwdJVj/VMQuw+oLRKu2mp03AV5n3CGTRRJyk395vw5i/oKjDOEVOYIU1NDwDUGXAuAqgAo4e2pBb6OnERQLX/nStMu1OpO1lCR1cX3tX3CqWAdiqPwyyuvtxUA/fO/LXOD1DzlyL77MM+UG7DjCaR3+mpkQxyaaEwbAO79wrTmoIwe5tjtAk5lX6kc7Em+5N71jo
3MUJYIt/F9JThb81Q8QpvqzxMuG2nSg7LQ5MGCHRYpl9mUH7Ax70dFLoHqY03t9itnPz5BC3qqIOy4Rcplm6j2WRVu+8XCBnG6/ynkq8fp7cdxPjPKMZOhGJhoG4lZveUeeMH8+wPCAcRCe10/Vybe1db02py5fXS7Xn6dHqgSAYj4Mobpxgbewpx79F8qSSUBLW2e34SJWDEQu0rusX
MU3YImLhowuknMhU0XHCB84/9Z6fl3me1m14GL6jTnmXZ6q2MnHpqDMHBo="
  region: "eu-west-2"  
  app: "next-boilerplate-dev"
  env: "next-boilerplate"
  bucket_name: "next-boilerplate-dev"